### ISSUE TITLE
Inventory GUI for 1.9

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#160]
![](http://media-minecraftforum.cursecdn.com/attachments/107/709/arrow.png)

Proposal that does not please me.

![inventory](https://cloud.githubusercontent.com/assets/401965/7474998/4e439f1e-f345-11e4-97d2-f21b711af1d1.png)

**Comment by CuddleWoozle** [comment]
I have an idea, but I won't be able to work on it until tomorrow or later.

I'm kinda thinking maybe we could do something other than the wooden boxes for this because it's starting to look like the inside of a shipping center.  XD  I was thinking maybe having some kind of cloth-like texture so it looks like it's showing what is on your back or something like that.  That's where a quiver should hang.  As to the shield...that kind of depends on what the shields look like.  We might be able to just put a 'ghost' image there, kind of like the armor placeholders that appear when you aren't wearing anything.

They might change things up further between now and when they release this.
