### ISSUE TITLE
 consistency problem in END

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#193]
beige :
![end_stone](https://cloud.githubusercontent.com/assets/401965/8580966/e9bc83b6-25bd-11e5-9745-7e5b1b5bf7c7.png)
red :
![obsidian](https://cloud.githubusercontent.com/assets/401965/8580974/f5fed2d2-25bd-11e5-85da-b42df4d6303c.png)![ender_pearl](https://cloud.githubusercontent.com/assets/401965/8581014/447d5adc-25be-11e5-910c-c9ece34b8ab6.png)
purple :
![endermite](https://cloud.githubusercontent.com/assets/401965/8581020/4d4ce146-25be-11e5-8fac-9dbfe2461872.png)
black and white :
![enderman](https://cloud.githubusercontent.com/assets/401965/8581024/5248e2bc-25be-11e5-8c2b-c0f0d053125e.png)

And more ... Do not match.

**Comment by lipki** [comment]
ping @CuddleWoozle

**Comment by CuddleWoozle** [comment]
...I'm unsure where you are going with this?

The colors aren't all the same?

The default colors are different.  There's beige/white endstone, green/blue trim on the end portal blocks, purple obsidian, blue/green ender pearls/eyes of ender, etc.

I don't think it's a problem to have color variations in these textures.  If they are share a common color scheme it will make the End look bland.

Obsidian makes sense to be being red/purple because within the realm of Minecraft it's created as cooling magma.  IRL Obsidian is commonly solid black and glass-like.

And the Endermen in SummerFields are a nod to "Slenderman", which is why they have no faces or glowy eyes.

**Comment by tobyplowy** [comment]
lipki Can this issue be closed?

**Comment by lipki** [comment]
No, the problem still exists.

**Comment by lipki** [comment]
https://github.com/orgs/SummerFields/teams/summerfields-contributor/discussions/2
