### ISSUE TITLE
Mc patcher is missing

### ISSUE THREAD

**Issue by FlorianDoyen95** [SummerFields/SummerFields#295]
Hello,

First, I use your ressourcepack since a long time and I love it, but since 1.10 relase, all textures aren't connected each other like grass, snow, pigs and squid have loose their différent textures and leaves aren't semi-transparent.

I suggest you to introduce the mcpatcher folder in your new ressourcepack from the 1.8 one.
Cureently, i'm making my own 1.11 ressourcepack by putting mcpatcher folder in the zip archive.

Thanks to your bautifull ressource pack and for reading my comment.

Snykeurs

**Comment by tobyplowy** [comment]
@FlorianDoyen95 thank you for reporting your problem this is not something for me but more for lipki

**Comment by tobyplowy** [comment]
@lipki ping

**Comment by lipki** [comment]
I chose to separate the standard pack and mcpatcher so that it is less heavy to download.
You can use two pack at the same time with minecraft without having to open the zip
Simply select both.

Now it's true that I have trouble updating mcpatcher, I forget, and I assume that users also forget to use it.

Maybe I should re-merge.

**Comment by FlorianDoyen95** [comment]
Hello,

Thanks you very much to take on your time to answer me, i forgot that we
can combine two packs...

I love your ressourcespack, you have all my support !

Snykeurs

Le 10 déc. 2016 2:23 PM, "Lepeltier kévin" <notifications@github.com> a
écrit :
