### ISSUE TITLE
License Change?

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#308]
Wuzzy says

> SummerFields is CC BY-SA-NC 4.0 :-(((((((
> It's not minecrafty anyways, so whatever.
> https://github.com/SummerFields/SummerF ... LICENSE.md
> 
> Seriously, Creative Commons should nuke these terrible -NC licenses, they are the pest.
> But maybe you can get the original SummerFields authors to change the license. Good luck.

I don't know what I licenses mean but can we do anything with this ( make it a licence where you can use it for whatever you want as long as you give credit I don't know if that exists)

**Comment by tobyplowy** [comment]
@lipki ping

**Comment by RobertZenz** [comment]
A short explanation, SummerFields is currently licensed under CC-BY-SA-NC, so you must adhere to the following rules:

  * BY: Always name the author.
  * SA: If you modify it, you must license the result it under this or a compatible license.
  * NC: You're not allowed to make money of this.

The license says this regarding NC:

 > ... reproduce and Share the Licensed Material, in whole or in part, for NonCommercial purposes only; and produce, reproduce, and Share Adapted Material for NonCommercial purposes only.

I'm not a lawyer, so I can't tell you what "Commercial" purposes are exactly. But you're for sure not allowed to sell the texture pack in any form. If you're allowed to sell a game which uses the texture pack, I can not say.

To change the license *all* copyright holders/authors, current and former, have to agree to that change. Well, not necessarily. You see, you can always license something more strict. For example, you can take something that is licensed under CC and license it under CC-SA. You can take something that is licensed under CC-SA and license it under CC-SA-NC. But you can't go back. Something that is licensed under CC-BY-SA-NC can only be relicensed by *all* copyright holders.

I do not see the point if relicensing SummerFields, though. Did Wuzzy also state what exactly his problem is with the license? Do they plan to sell a game which wants to use SummerFields?

**Comment by tobyplowy** [comment]
@RobertZenz Wuzzy is One Of Those People Who really likes open source stuff (Linux PC and all programs on the PC are open source)

That would make a lot of Sense with the quote Underneath

> Seriously, Creative Commons should nuke these terrible -NC licenses, they are the pest.

I dount think it's Because he cant Make Money Of It (That's really unlikely because what he's making is %100 free) 

Take a look at wuzzy's project https://forum.minetest.net/viewtopic.php?f=50&t=16407

**Comment by MuhdNurHidayat** [comment]
The only thing it's problematic is because it's not backward compatible with any other open license/free license while being a open license itself, but it did creates confusion to the extend that -NC is regarded as not a real open license...

Try reading some articles on -NC:
1. http://esr.ibiblio.org/?p=4559
2. https://blog.okfn.org/2013/01/08/consequences-risks-and-side-effects-of-the-license-module-non-commercial-use-only-2/
3. https://scholarlykitchen.sspnet.org/2015/03/13/more-creative-commons-confusion/
4. https://www.techdirt.com/articles/20100901/21000710869.shtml

and search for more...

**Comment by lipki** [comment]
Whatever the license, the "nc" is non-negotiable.

**Comment by lipki** [comment]
My answer is short, and gives the impression that I am not open to argument :)
This is not the case.
The fact is that commercial use of the summerfield requires the agreement of the original author, and the current license allows it.
And protects the author from commercial use without agreement.

And if another license offers the same benefits, we can study the issue.

**Comment by tobyplowy** [comment]
@lipki can you please ask LithiumSound

**Comment by RobertZenz** [comment]
> (Why are there always people to come discuss licensing, and nobody to make contributions ???)

I can only speak for myself, but I suck at anything that involves art...but I do know quite a lot about FLOSS and associated licenses. And there seemed to be some confusion initially, so I tried to clear that up.

**Comment by tobyplowy** [comment]
@lipki I make contributions, not that much anymore but Still do ( I'm currently working on Summerfields 16x16 so that's why I'm not doing much contributions sorry lipki should I work harder?)

**Comment by Wuzzy2** [comment]
Hi all! I'm the one behind MineClone 2. Maybe I should explain my motivations.

The point of MineClone 2 is to be 100% free software clone of Minecraft.
One aspect of [free software](https://www.gnu.org/philosophy/free-sw.html) is to be usable for any purpose. A clause which forbids commercial use violates this. So I can't use CC BY-SA-NC, because if I do, MineClone 2 will cease to be free software. MineClone 2 exists because Minecraft is proprietary software. If Minecraft would be free software, MineClone 2 would probably have never been created.

So long story short, if this license stays, I will never use this texture pack in MineClone 2. Being free software is a core goal of MineClone 2, and I will not drop this goal in favor of a texture pack. I'd rather take a different texture pack.

I think CC BY-SA-NC material is not a contribution to the commons, so I think the only safe way to treat CC BY-SA-NC material is to treat is as if it would be just under plain old copyright, even if you *think* you're not commercial. One public radio (run by tax money and such, not owned by a company at all) in Germany was once sued for using CC BY-SA-NC material because they were to be considered a “commercial entity” which was very surprising.

I don't know why you chose this license, but here are some comments:

* If you fear you will be commercially exploited, CC BY-SA is already doing a good job in protecting you
* If you want to destroy capitalism, licenses will not do a real change. Capitalists will just use something else
* If the thought that other people can make money on *your* hard work makes you sick and you think this is evil, think again: There are actually beneficial uses as well.

Here's a VERY good article about the problems with NC licensing: http://freedomdefined.org/Licenses/NC

That having said, I'm not trying to convince you to switch the license nor will I attempt to request a “special permission” just for MineClne 2 because I will simply pick another texture pack then. So if you disagree with the points stated above, whatever.

I'm probably as uncapitalistic as you can get. I don't plan to sell MineClone 2 or earn any money with it. I rarely sold anything in my entire life. IIRC the last time I sold something was my old bike over 15 years ago.
But if someone thinks he or she wants to make a buck of MineClone 2, I don't care (because it's free software). I think of something like someone wants to burn it on CDs and sell those to make some extra cash. I wouldn't mind, I know there are people out there who need money more than I do.

> while being a open license itself, but it did creates confusion to the extend that -NC is regarded as not a real open license...

I am not confused at all, I know perfectly way what this license means. -NC is rightfully regarded as a non-open license because it fails the basic criteria of the free software definition and the open source definition.

**Comment by lipki** [comment]
LithiumSound does not answer for a long time, but it remains the author.
@RobertZenz does not take my reflection badly, it was not bad.
@tobyplowy this remark does not concern you, obviously, for me today the Summerfield, it's us both.
@ Wuzzy2
Nothing to say, I agree with you, and I understand your choices.
As I said the NC is not negotiable, unless the author says so.
Other projects wanted to use the Summerfield, and had the same problem.

Your goal is to reproduce Minecraft, you should be able to find a texture pack closer to that of Minecraft, without this license constraint.
On our side, we will surely provide a version compatible with your games, which players will be able to install on their own.

Then I think of other things.
@tobyplowy working on a 16x16 version, I will probably help, this version will be entirely our, so we can consider another license.

**Comment by RobertZenz** [comment]
@lipki No offence taken, I consider your "criticism" valid, though, that was why I responded to it.

**Comment by tobyplowy** [comment]
@lipki I see you didn't get the License 0_o

**Comment by lipki** [comment]
The current license does very well the job.
