### ISSUE TITLE
Should we add models for some normal blocks?

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/SummerFields#457]
Like gravel can get a model like this for example
![image](https://user-images.githubusercontent.com/16853304/46511113-f1869980-c84c-11e8-854d-9c5ffd92d3c2.png)

And maybe for grass we can have some small pebbles
Or some short grass stick out of the top of the grass block.

Ore can use this too...
Here's an image from the Minecraft Dungeons trailer.
![image](https://user-images.githubusercontent.com/16853304/46511280-fef05380-c84d-11e8-9be5-9ad74d2efd7e.png)
I really like that redstone.
Maybe something like this can be done.
![image](https://user-images.githubusercontent.com/16853304/46511502-49260480-c84f-11e8-90a7-265ddd603552.png)
It uses multiple layers stacked on top of each other, like this.
![image](https://user-images.githubusercontent.com/16853304/46511534-6eb30e00-c84f-11e8-845a-c1947a762263.png)
It gives a 3D effect.

**Comment by lipki** [comment]
So, several things.

The new models are very greedy resource.
in addition to weighing down the pack.
So I prefer to go with parcimony.

For the moment I chose the blocks that really needed it ... from my point of view.
Because the block was just a face in the void:
iron bars
rails
sugar cane

To provide additional information:
piston
note block

To bring relief:
chorus
doors
trapdoor

So ok to improve the blocks, but need a good reason.
If the original block does the job and is not ugly, we do not need to change it.
It's just my opinion (it's not an order :))

So, for the gravel.
It should be remembered that only 0 / 22.5 / 45 angles can be made on a single axis per block.
To create a small pebble flat, why not.

I like redstone crystals, of dungeons.
It remains to be seen how the add.

And for the relief effect of minerals, it's interesting, I'll try.

**Comment by lipki** [comment]
Nop, it will not work, we can not use transparency for extra layers.
We have to make each little cube one by one.

**Comment by lipki** [comment]
Download https://blockbench.net/
You should not have trouble, and you will be better aware of what you can do.

And to make 3d models of mobs, it will be easier.

**Comment by tobyplowy** [comment]
@lipki Alright well I think that this can be closed :)
