### ISSUE TITLE
[1.15.2] All wall models show as invalid textured full blocks

### ISSUE THREAD

**Issue by puzzlecube** [SummerFields/SummerFields#631]
I have tracked this problem down to commit 27fee17eb685b6c9a86ce4383a2eb15065c23128 when wall models were last changed. It seems to have broken wall models when used with Minecraft 1.15.2. Fence-like models are not broken.
![2020-03-22_14 50 29](https://user-images.githubusercontent.com/17504638/77259030-9ddc5b80-6c4c-11ea-95a3-5f0617aa336c.png)
These are supposed to be stone brick walls but I have seen this problem with cobblestone walls too.
![2020-03-22_15 02 22](https://user-images.githubusercontent.com/17504638/77259246-39ba9700-6c4e-11ea-87da-33784c7ccc33.png)
This happens to all walls in all possible variations and directions.

**Comment by lipki** [comment]
Yes sorry for that, it's a bug with 1.16 which is supposed to be compatible, but which is not.

I will find a solution, no doubt.
As soon as I find the time.

**Comment by supawiz6991** [comment]
Out of curiosity after experiencing this issue as well...looking at the json code differences from 1.15.2 and 1.16 for walls in general. It looks like some pretty big changes which I'm guessing is to facilitate the "No more gaps in stacked walls" change.
I would guess the issue is 1.15.x doesn't understand the new format meant for 1.16.

ON a side note: I love this project and have been using it since just before Lithium Sound left. Keep up the good work!

**Comment by lipki** [comment]
tried to run with both versions.
I do not arrive, it is not permissive enough.
Too bad, I have upgraded to version 1.15 for now.
