### ISSUE TITLE
[1.20] Torch flower

### ISSUE THREAD

**Issue by lipki** [SummerFields/SummerFields#809]
![torchflower](https://user-images.githubusercontent.com/401965/219158530-ea75a87b-9ee5-4e6b-8107-3b2c112cd8c9.png)![torchflower_crop_stage0](https://user-images.githubusercontent.com/401965/219158536-dfc72816-2499-4b3f-8ac1-002fe6ee0eb6.png)![torchflower_crop_stage1](https://user-images.githubusercontent.com/401965/219158539-69e9a23c-6e55-4fec-bac4-6df397871651.png)![torchflower_crop_stage2](https://user-images.githubusercontent.com/401965/219158545-5339dfbf-de22-4bf8-b4a1-56357b81652b.png)

![torchflower_seeds](https://user-images.githubusercontent.com/401965/219163130-6525cd41-b3ab-45c0-900b-c9428962e0f1.png)

**Comment by Physignatily** [comment]
![torchflower](https://user-images.githubusercontent.com/74598365/219534741-ab984d14-4210-4870-8bd4-44adfc67fbd5.png)![torchflower_crop_stage0](https://user-images.githubusercontent.com/74598365/219534750-15196cbd-21d8-480d-85c3-9066b70e28b6.png)![torchflower_crop_stage1](https://user-images.githubusercontent.com/74598365/219534755-ef493dbe-06d6-45fb-9400-3a64bacfb1a9.png)![torchflower_crop_stage2](https://user-images.githubusercontent.com/74598365/219534764-6ba63867-d571-4e74-aa69-c582a8b706db.png)
![torchflower_seeds](https://user-images.githubusercontent.com/74598365/219534770-02888cd4-30da-42d0-9501-a1a948964395.png)

Ok, short explanation: Torchflower is a subspecies of bromelia and bromelias often replicate themself through seedlings instead of seeds. Therefore i didn't aim for seeds. Also the sniffers dig them out of the ground. So i guess some sprouted roots are ok. :D

**Comment by Physignatily** [comment]
![torchflower](https://user-images.githubusercontent.com/74598365/219535586-bf33ef91-63bd-442b-bde5-900d1b80a585.png)![torchflower_crop_stage0](https://user-images.githubusercontent.com/74598365/219535587-3202b58a-acf2-40f0-ac77-204e43660b6f.png)![torchflower_crop_stage1](https://user-images.githubusercontent.com/74598365/219535589-91b9df81-797f-4b2a-a41f-aaf763d664b7.png)![torchflower_crop_stage2](https://user-images.githubusercontent.com/74598365/219535590-5f3a6844-cbb9-4456-8d56-435920fd580f.png)
![torchflower_seeds](https://user-images.githubusercontent.com/74598365/219535795-d20545e7-3b94-4eae-8944-13d3116bfb3c.png)


Ok, short explanation: Torchflower is a subspecies of bromelia and bromelias often replicate themself through seedlings instead of seeds. 
Therefore i didn't aim for seeds. 

Also the sniffers dig them out of the ground. So i guess some sprouted roots are ok. :D

**Comment by lipki** [comment]
It suits me perfectly, it's beautiful.

**Comment by lunapanshiel** [comment]
bromeliads also come in a huge array of colors, i would recommend using blockstates to randomize them to make farms/fields look more lush

![12-Amazing-Benefits-of-Bromeliad-Plants](https://user-images.githubusercontent.com/27765468/220776895-9e457694-9f35-4e31-bf3e-29b3058bce36.jpeg)
![bromelaids__61566 1642598994](https://user-images.githubusercontent.com/27765468/220776921-8a42e26b-375c-453b-845e-1b7f513d6740.jpg)

**Comment by lipki** [comment]
It's a good idea, and if you want, feel free to do the textures.
Me, I'll wait to see what Mojang will do with it first.
