### ISSUE TITLE
[Model bug] Texture bug under the wolf's head

### ISSUE THREAD

**Issue by ORN-Fox** [SummerFields/SummerFields#914]
Hi, I noticed a problem while looking at the textures of the new wolves added in 1.20.5. Below the wolf's head, the mouth is not textured and you can see into the wolf.

![2024-04-24_00 00 09](https://github.com/SummerFields/SummerFields/assets/49326517/dd6dbbd6-1c55-4f70-a13c-fcff32676e8a)

**Comment by lipki** [comment]
It's intentional, it allows for the lips and teeth to be cut out.
Moreover, the back of the mouth is colored in black to serve as the throat background.
This was already the case in the original texture.


![hop](https://private-user-images.githubusercontent.com/401965/311018907-670114b4-c9ef-4072-b87d-7de0363a66ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNDQ2OTAsIm5iZiI6MTcxNDM0NDM5MCwicGF0aCI6Ii80MDE5NjUvMzExMDE4OTA3LTY3MDExNGI0LWM5ZWYtNDA3Mi1iODdkLTdkZTAzNjNhNjZjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQyMjQ2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjIzMDQ0YWJjYmJmNTYzN2NmNzQxZGU3NmYxYzNmMTgxODYzZDQzM2Y4YzFhZTBiYTc2OTkxZjUwYWJkNmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.thxLNR3-Kgc2of-dm3whOzb35Rt9i6TWYoiG19axKbs)

**Comment by lipki** [comment]
Thanks to your team for taking the time to look for errors in the pack. Even though I say it's intentional, it's not necessarily right, and maybe we can do better, I'm open to change.
